In [183]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
from proj1_helpers import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [28]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../Data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [101]:
def build_poly2(x, degree):
    """polynomial basis functions for input data x, for j=0 up to j=degree."""
    size = (x.shape[0])*(degree+1)
    phi = np.full((1, size), 0.0)
    
    for i in range(0, x.shape[0]):
        for j in range(0, degree+1):
            index = j + i*(degree+1)
            np.put(phi, index, np.power(x[i], j))

    return phi

build_poly2(np.array([1,2,3]), 2)

array([[ 1.,  1.,  1.,  1.,  2.,  4.,  1.,  3.,  9.]])

In [124]:
# Make tX useful with my build_poly func

degree = 2
#polyX = np.full((tX.shape[0], tX.shape[1] * (degree+1)), 0.0)
polyX = list()
for row in tX:
    polyX.append(build_poly2(row, degree))

PolyXNP = np.array(polyX)
PolyXNP2 = PolyXNP.reshape((PolyXNP.shape[0], PolyXNP.shape[2]))


In [163]:

PolyXNP.shape[2]

90

In [164]:

PolyXNP2.shape

(250000, 90)

## Training:

In [165]:
Fused = np.c_[y, PolyXNP2]

In [174]:
model_id = (degree+1)*23 - 1
np.unique(Fused[:, model_id])

array([ 0.,  1.,  2.,  3.])

In [175]:
from ml_functions import *

#First we build a polynomial model to represent the features
#phi = build_poly(tX, 1)

Fused_0 = Fused[Fused[:,model_id] == 0.0]
Fused_1 = Fused[Fused[:,model_id] == 1.0]
Fused_2 = Fused[Fused[:,model_id] == 2.0]
Fused_3 = Fused[Fused[:,model_id] == 3.0]

gamma = 0.1
max_iters = 500
w_initial = np.full((tX.shape[1]), 0.0)
'''w_initial, gamma,  max_iters'''

w1 = ridge_regression(Fused_0[:,0], Fused_0[:,1:Fused_0.shape[1]], 0.01)
w2 = ridge_regression(Fused_1[:,0], Fused_1[:,1:Fused_1.shape[1]], 0.01)
w3 = ridge_regression(Fused_2[:,0], Fused_2[:,1:Fused_2.shape[1]], 0.01)
w4 = ridge_regression(Fused_3[:,0], Fused_3[:,1:Fused_3.shape[1]], 0.01)

#weights = ridge_regression(y, tX, 0.01)

weights = (w1, w2, w3, w4)
weights
#w = logistic_regression(y,tX,gamma,max_iters)

(array([ -8.39830534e-01,  -1.00600836e-03,  -9.92527245e-07,
         -7.96365699e-15,  -1.42065873e-02,   8.22352758e-05,
         -2.75330707e-15,  -1.76981933e-02,   1.98272206e-05,
         -1.00546635e-14,  -3.87002745e-04,  -1.20437296e-04,
         -1.00546635e-14,   3.68264236e-11,  -1.56291765e-08,
         -1.00546635e-14,   3.57770831e-11,  -1.56291765e-08,
         -7.55288027e-15,   3.57770831e-11,  -1.56291765e-08,
         -7.55288027e-15,   8.46410973e-02,   1.17797714e-01,
          1.49570126e-27,  -3.85946556e-04,   1.33834371e-04,
          1.48278342e-27,   1.62167414e-02,   8.49304766e-05,
          1.50721711e-27,  -1.18640226e-01,   3.16247769e-02,
          1.56903841e-27,   2.64761069e-04,  -3.19222012e-02,
          1.56113193e-27,   2.54798657e-11,  -1.56291765e-08,
          1.57262843e-27,   1.56125604e-02,  -2.03024116e-04,
          1.57704251e-27,   7.16681738e-04,  -1.87079199e-02,
          1.56414342e-27,   2.29611565e-06,   4.34033719e-04,
        

## Generate predictions and save ouput in csv format for submission:

In [176]:
DATA_TEST_PATH = '../Data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [184]:
OUTPUT_PATH = '../Data/result3.csv' 
# TODO: fill in desired name of output file for submission
y_pred = predict_labels3(weights, tX_test, degree)
print(y_pred.shape)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

(568238,)
