First do everything in Python

In [5]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
from sklearn import preprocessing

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../Data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [ ]:
tX.shape

In [6]:
tX_scaled = preprocessing.scale(tX)

In [10]:
tX_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [21]:
tX_scaled.mean(axis=0)

array([ -2.50602916e-15,   4.49575133e-15,  -3.48448848e-15,
         7.18646387e-15,  -2.36304576e-14,  -3.26035021e-15,
         1.26038877e-14,   2.16223188e-14,   6.40057962e-15,
         2.86143687e-15,  -6.98486646e-15,   3.63458152e-15,
        -1.27422117e-14,  -5.95722149e-15,   1.35646161e-16,
         7.13136217e-17,   2.58023760e-14,  -1.06327391e-16,
        -1.87188487e-16,   8.24115935e-15,   1.41040513e-16,
        -8.99509711e-15,  -6.01698247e-16,  -4.92204144e-15,
         3.11615622e-15,  -1.67606551e-15,  -9.40773592e-15,
         1.79148900e-14,  -5.09692022e-15,  -1.77122317e-15])

In [11]:
tX_normalized = preprocessing.normalize(tX_scaled, norm='l2')

In [13]:
tX_normalized

array([[ 0.08424028,  0.01247536,  0.07443017, ...,  0.28605061,
         0.28455068,  0.07531202],
       [ 0.12311696,  0.1316473 ,  0.12870024, ..., -0.15234416,
        -0.15234425, -0.06524406],
       [-0.33675062,  0.4602376 ,  0.15795104, ..., -0.09209584,
        -0.09209589, -0.0423441 ],
       ..., 
       [ 0.1104989 ,  0.09281144, -0.03803639, ..., -0.18583613,
        -0.18583624, -0.09214316],
       [ 0.07326994, -0.17480727, -0.06265284, ..., -0.13221667,
        -0.13221675, -0.15415182],
       [-0.46626531,  0.1326954 , -0.05056287, ..., -0.12751601,
        -0.12751609, -0.1486713 ]])

In [15]:
tX = tX_normalized

## Training:

In [16]:
from ml_functions import *

#First we build a polynomial model to represent the features
#phi = build_poly(tX, 2)

gamma = 0.1
max_iters = 30
w_initial = np.full((tX.shape[1]), 0.0)
'''w_initial, gamma,  max_iters'''
w = least_squares(y, tX)
w = logistic_regression(y,tX,gamma,max_iters)

In [17]:
w
weights = w

## Generate predictions and save ouput in csv format for submission:

In [18]:
DATA_TEST_PATH = '../Data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

Processing test data

In [19]:
tX_test_scaled = preprocessing.scale(tX_test)
tX_test_normalized = preprocessing.normalize(tX_test_scaled, norm='l2')
tX_test = tX_test_normalized

In [25]:
tX_test

array([[-0.44235117,  0.16196604, -0.26713666, ..., -0.12112799,
        -0.12112806, -0.14062798],
       [ 0.10196931,  0.13747681,  0.04501522, ..., -0.17104332,
        -0.17104342, -0.06963535],
       [ 0.09754712,  0.04682163,  0.08953039, ..., -0.15242783,
        -0.15242792, -0.17696668],
       ..., 
       [ 0.0913366 , -0.26270884, -0.09308614, ..., -0.15116266,
        -0.15116275, -0.17549783],
       [ 0.09828141, -0.22676242, -0.09612645, ..., -0.1758375 ,
        -0.17583761, -0.11815167],
       [ 0.07953901,  0.19949546, -0.01981061, ..., -0.14668002,
        -0.1466801 , -0.17029355]])

In [24]:
tX_test.shape

(568238, 30)

In [22]:
OUTPUT_PATH = '../Data/result_normalized.csv' 
# TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
print(y_pred.shape)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

(568238,)


## Do some Testing Accuracy so don't have to submit on kaggle