In [88]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
from proj1_helpers import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../Data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [105]:
# Make tX useful with my build_poly func

degree = 2
#polyX = np.full((tX.shape[0], tX.shape[1] * (degree+1)), 0.0)
polyX = list()
for row in tX:
    polyX.append(build_poly2(row, degree))

PolyXNP = np.array(polyX)
PolyXNP2 = PolyXNP.reshape((PolyXNP.shape[0], PolyXNP.shape[2]))


KeyboardInterrupt: 

## Training:

In [90]:
Fused = np.c_[y, PolyXNP2]

In [103]:
model_id = (degree+1)*23 - 1
np.unique(Fused[:, model_id])

array([ 0.,  1.,  2.,  3.])

In [55]:
from ml_functions import *

w = logistic_regression_test(y, tX, 0.01, 200)

In [96]:
from ml_functions import *

#First we build a polynomial model to represent the features
#phi = build_poly(tX, 1)

Fused_0 = Fused[Fused[:,model_id] == 0.0]
Fused_1 = Fused[Fused[:,model_id] == 1.0]
Fused_2 = Fused[Fused[:,model_id] == 2.0]
Fused_3 = Fused[Fused[:,model_id] == 3.0]

gamma = 0.01
max_iters = 500

w1 = logistic_regression_test(Fused_0[:,0], Fused_0[:,1:Fused_0.shape[1]], gamma, max_iters)
w2 = logistic_regression_test(Fused_1[:,0], Fused_1[:,1:Fused_1.shape[1]], gamma, max_iters)
w3 = logistic_regression_test(Fused_2[:,0], Fused_2[:,1:Fused_2.shape[1]], gamma, max_iters)
w4 = logistic_regression_test(Fused_3[:,0], Fused_3[:,1:Fused_3.shape[1]], gamma, max_iters)

#weights = ridge_regression(y, tX, 0.01)

weights = (w1, w2, w3, w4)

#w = logistic_regression(y,tX,gamma,max_iters)

In [97]:
weights

(array([[  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [ -3.86510348e+02],
        [ -2.00608798e+04],
        [ -1.49060936e+06],
        [ -3.86510348e+02],
        [ -3.18934198e+04],
        [ -3.07537608e+06],
        [ -3.86510348e+02],
        [ -5.38101887e+03],
        [ -2.10598891e+05],
        [ -3.86510348e+02],
        [  3.86123838e+05],
        [ -3.85737714e+08],
        [ -3.86510348e+02],
        [  3.86123838e+05],
        [ -3.85737714e+08],
        [ -3.86510348e+02],
        [  3.86123838e+05],
        [ -3.85737714e+08],
        [ -3.86510348e+02],
        [ -1.06081924e+03],
        [ -3.06424881e+03],
        [ -3.86510348e+02],
        [ -5.38101885e+03],
        [ -2.10598891e+05],
        [ -3.86510348e+02],
        [ -3.00740130e+04],
        [ -2.54905694e+06],
        [ -3.86510348e+02],
        [ -4.99335065e+02],
        [ -7.75395289e+02],
        [ -3.86510348e+02],
        [  3.23012740e+02],
        [ -6.6431331

In [99]:
weights2 = (w1.reshape((w1.shape[0],)), w2.reshape((w2.shape[0],)),w3.reshape((w3.shape[0],)), w4.reshape((w4.shape[0],)))



In [104]:
weights2

(array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -3.86510348e+02,  -2.00608798e+04,  -1.49060936e+06,
         -3.86510348e+02,  -3.18934198e+04,  -3.07537608e+06,
         -3.86510348e+02,  -5.38101887e+03,  -2.10598891e+05,
         -3.86510348e+02,   3.86123838e+05,  -3.85737714e+08,
         -3.86510348e+02,   3.86123838e+05,  -3.85737714e+08,
         -3.86510348e+02,   3.86123838e+05,  -3.85737714e+08,
         -3.86510348e+02,  -1.06081924e+03,  -3.06424881e+03,
         -3.86510348e+02,  -5.38101885e+03,  -2.10598891e+05,
         -3.86510348e+02,  -3.00740130e+04,  -2.54905694e+06,
         -3.86510348e+02,  -4.99335065e+02,  -7.75395289e+02,
         -3.86510348e+02,   3.23012740e+02,  -6.64313316e+02,
         -3.86510348e+02,   3.86123838e+05,  -3.85737714e+08,
         -3.86510348e+02,  -1.40459449e+04,  -6.07384102e+05,
         -3.86510348e+02,   7.99498695e+00,  -5.58623759e+02,
         -3.86510348e+02,   8.10090096e+00,  -1.27689001e+03,
        

## Generate predictions and save ouput in csv format for submission:

In [60]:
DATA_TEST_PATH = '../Data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [71]:
OUTPUT_PATH = '../Data/resultLogisticRegr1.csv' 
# TODO: fill in desired name of output file for submission
y_pred = predict_labels3(weights2, tX_test, degree)
print(y_pred.shape)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

(568238,)


In [72]:
print("bana")

bana
